### ISSUE TITLE
Might be good to add docs on the minimum version of Node.js we support

### ISSUE THREAD

**Issue by palewire** [datadesk/baker#1053]
I had a test user run into this issue with an outdated version. Would be good to get into the README or something.

**Comment by palewire** [comment]
cc @rdmurphy

**Comment by palewire** [comment]
Added some other versions to our tests, including the bleeding edge version. Doesn't fix this ticket, but it does seem like a good step forward.

https://github.com/datadesk/baker/actions/runs/1464170336

**Comment by rdmurphy** [comment]
Oh huh! Someone who was using something `< v12`?

I'd recommend sticking to whatever is compatible with Node.js' [long term support (LTS) matrix](https://nodejs.org/en/about/releases/). Currently `v12` is the lowest actively supported version.

One potential catch here — Baker is already using [dynamic imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports) in Node, which requires at a minimum `v12.20.0`, which means not every `v12` is valid. In general that means this [document is probably the best guiding resource](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) — any version of Node that fully supports the modules spec should be good. From the doc:

> You also need to make sure you're on the latest minor version of Node.js. At minimum Node.js 12.20, 14.14, or 16.0.

Because Node uses odd number major releases as short six-month feature pushes I'd probably never promise/aspire to have those aggressively supported because Node stops supporting them so quickly. (Of course if it works in `v16`, should have zero problems in `v17`.)

**Comment by palewire** [comment]
I had a feeling you'd have a better answer to this than me. I'll adapt your guidance here and stick it in the README.

**Comment by rdmurphy** [comment]
I'll add that another benefit of latching on to this support matrix is that it syncs up nicely with #1033 — when that happens Baker shouldn't break for anyone because it's the same minimum versions for that.
